name: datetime_utils 
description: "datetime_utils"
version: 1.0.0
publish_to: pub.dev
# homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

